package ast;

public enum TipoE {
	  SUMA,MUL,INT, FLOAT, DIVREAL, DIVENT, MODULO, SIZE,
	  NOT, OR, AND, IGUALIGUAL, MAYOR, MENOR, MAYORIGUAL, 
	  MENORIGUAL, DISTINTO, CORCHETES, PUNTO, TRUE, FALSE, 
	  CARACTER, IDEN, VECTOR, SUMAUNARIA, RESTAUNARIA, RESTA,
	  LLAMADAFUN, ACCESOPUNTERO, NEW
	}
