
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jun 15 16:24:19 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 42;
  public static final int CREAVECTOR = 4;
  public static final int DISTINTO = 30;
  public static final int DIVENT = 21;
  public static final int CHAR = 57;
  public static final int PUNTOYCOMA = 39;
  public static final int PCIERRE = 36;
  public static final int CASE = 7;
  public static final int RESTA = 18;
  public static final int INT = 55;
  public static final int FOR = 52;
  public static final int NOT = 25;
  public static final int MENORIGUAL = 27;
  public static final int AND = 23;
  public static final int IGUAL = 37;
  public static final int CARACTER = 50;
  public static final int FUN = 12;
  public static final int OR = 24;
  public static final int BOOL = 56;
  public static final int CALL = 9;
  public static final int SUMA = 17;
  public static final int TYPEDEF = 15;
  public static final int IF = 53;
  public static final int AMPERSAND = 44;
  public static final int MAYORIGUAL = 28;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int SIZE = 5;
  public static final int TRUE = 2;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int COMA = 38;
  public static final int MUL = 19;
  public static final int MODULO = 22;
  public static final int MENOR = 54;
  public static final int BREAK = 8;
  public static final int VECTOR = 46;
  public static final int SWITCH = 6;
  public static final int REAL = 49;
  public static final int MAYOR = 26;
  public static final int ENT = 48;
  public static final int PAP = 35;
  public static final int BARRA = 34;
  public static final int ELSE = 10;
  public static final int CORCHETECIERRE = 41;
  public static final int PUNTO = 31;
  public static final int ENUM = 16;
  public static final int IDEN = 47;
  public static final int IGUALIGUAL = 29;
  public static final int WHILE = 51;
  public static final int DEFAULT = 43;
  public static final int LLAVESAP = 32;
  public static final int FLOAT = 58;
  public static final int LLAVESCIERRE = 33;
  public static final int CORCHETEAP = 40;
  public static final int PROC = 11;
  public static final int FALSE = 3;
  public static final int STRUCT = 14;
  public static final int DIVREAL = 20;
}

